
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: poetry install
  displayName: 'Install Dependencies'

- script: poetry run pytest
  displayName: 'Run Tests'

